### ISSUE TITLE
Customize list of views inspector attaches to.

### ISSUE THREAD

**Issue by JeromeLam** [tomgreenfield/adapt-inspector#1]
Depending on the theme used, it may be possible for the inspector elements to overlap (mainly page and article and the first block).  Would it make sense to allow the list of view types inspector hooks on to be customized?

I've currently added this to my local build as I'm only interested in using inspector for blocks and components.  I can submit a PR for this if it makes sense.

Let me know, and thanks for providing such a great component!

**Comment by tomgreenfield** [comment]
Hi and thanks for your feedback!

I've added an optional attribute in https://github.com/tomgreenfield/adapt-inspector/commit/79f1bf8fb64e608944e6d827f5e8bc8b5813300e named `_elementsToInspect`. This can be an array of strings to override the default views on which Inspector renders i.e.
```json```
"_elementsToInspect": [
	"block",
	"component"
]
```

**Comment by JeromeLam** [comment]
This is perfect.  Thanks!
