### ISSUE TITLE
would be useful to have a prompt to the user to enter a summary

### ISSUE THREAD

**Issue by moloko** [tomgreenfield/adapt-inspector#11]
Because Inspector auto-populates the TRAC ticket summary with '_componentId_ (page _pageId_)' people seem to forget that they need to include a summary of the issue in the summary field rather than just putting it in the description field - so when you view the ticket report you just get a long list of component ids.

Amending it to include a prompt like 'please enter a short summary of the issue here' might help to get people to complete the ticket summary field properly

**Comment by tomgreenfield** [comment]
Will look into making the summary completely flexible.

**Comment by moloko** [comment]
@tomgreenfield I need to do this for a project so will share that when done

**Comment by moloko** [comment]
solved by the new `_params` setting
