### ISSUE TITLE
Adapt 2.0 - Missing Schema

### ISSUE THREAD

**Issue by LukaszGrela** [tomgreenfield/adapt-inspector#5]
The new Adapt build has the schema test step and it fails on this extension with the following message:

```
Running "schema-defaults" task
Warning: Unable to read "src/extensions/adapt-inspector/properties.schema" file
(Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```
Should this extension have schema? or this is the issue with the Adapt?

**Comment by tomgreenfield** [comment]
Thanks for raising this Lukasz. This involves a fix to the Grunt task which you can follow [here](https://adaptlearning.atlassian.net/browse/ABU-1015).
